# -*- coding: utf-8 -*-
"""Kelompok Terabyte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkGeziu-Stl9YOlC44h2rdt-zyVVWm_O
"""

!pip install requests pandas

import requests
import pandas as pd
import numpy as np

url = "https://www.lazada.co.id/catalog/?ajax=true&q=wardah"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
data = response.json()

items = data.get("mods", {}).get("listItems", [])

produk = []
harga = []
lokasi = []
rating = []


for item in items:
    produk.append(item.get("name"))
    harga.append(item.get("price"))
    lokasi.append(item.get("location"))
    rating.append(item.get("ratingScore"))

df = pd.DataFrame({
    "Produk": produk,
    "Harga": harga,
    "Lokasi": lokasi,
    "Rating": rating,
})

df

df.describe()

df.sort_values("Harga")

df.to_csv("lazada_wardah.csv", index=False)

"""# **INTERPRETASI DAN PENJELASAN**

Metode yang digunakan pada pengumpulan data ini adalah metode web scraping untuk mengambil data produk dari website Lazada secara otomatis dengan bantuan bahasa pemrograman Python.

> Web scraping merupakan teknik penumpulan data dari sebuah situs web dengan cara mengakses struktur data yang tersedia pada halaman tersebut, kemudian mengekstrak informasi yang dibutuhkan.

Pada program ini, kami menggunakan beberapa library Python, yaitu

> 'requests' digunakan untuk mengirim HTTP request untuk melakukan pengambilan data dari website,

> 'pandas' untuk mengolah data dan menyusun data hasil scraping menjadi bentuk tabel (dataframe) sehingga lebih mudah dianalisis,

>'numpy' untuk membantu operasi numerik dan manipulasi array.


Selanjutnya, program meminta alamat URL yang akan dijadikan sumber data karena URL tersebut langsung mengarah pada hasil pencarian produk Wardah di Lazada.

Pada program kami juga menambahkan 'headers request' untuk menyamarkan request Python karena website e-commerce biasanya memiliki sistem keamanan untuk mendeteksi bot scraping. Oleh karena itu, program kami menambahkan User-Agent agar server menganggap permintaan berasal dari browser biasa.

Setelah itu program mengirimkan permintaan ke server Lazada menggunakan fungsi 'requests.get()'. Hasil dari permintaan tersebut kemudian disimpan dalam variabel response.

Data yang diterima dari server masih dalam format JSON, sehingga pada tahap berikutnya data tersebut dikonversi menggunakan fungsi 'response.json()'. Proses ini mengubah data menjadi struktur data Python berupa dictionary yang dapat diakses berdasarkan key tertentu. Dari struktur JSON tersebut, informasi produk berada pada bagian mods yang kemudian di dalamnya terdapat 'listItems' yang berisi daftar produk hasil pencarian.

Setelah mendapatkan daftar produk, program kemudian membuat beberapa list kosong yang digunakan untuk menampung informasi penting dari setiap produk. Informasi yang diambil meliputi nama produk, harga produk, lokasi penjual, dan rating produk. Program kemudian melakukan perulangan menggunakan for loop untuk membaca setiap item produk yang terdapat pada listItems. Pada setiap iterasi, program mengambil data yang diperlukan menggunakan fungsi 'get()' agar proses tetap berjalan meskipun terdapat data yang kosong atau tidak tersedia pada suatu produk.

Setiap informasi yang berhasil diambil kemudian dimasukkan ke dalam list yang telah disiapkan sebelumnya. Setelah seluruh produk diproses, data yang tersimpan pada list tersebut digabungkan dan diubah menjadi sebuah DataFrame menggunakan library pandas. DataFrame ini memiliki struktur tabel dengan lima kolom utama, yaitu produk, harga, lokasi, dan rating. Dengan bentuk DataFrame ini, data menjadi lebih mudah untuk dianalisis, diproses lebih lanjut, maupun disimpan dalam bentuk file seperti CSV.

> Berdasarkan dataset yang dihasilkan, program berhasil mengumpulkan 40 data produk Wardah dari hasil pencarian di Lazada.

> Setiap baris pada dataset mewakili satu produk dengan informasi nama produk, harga, lokasi penjual, serta rating dari pengguna.

> Dari data yang diperoleh dapat terlihat bahwa harga produk Wardah pada hasil pencarian tersebut memiliki rentang yang cukup bervariasi, mulai dari sekitar Rp20.000 hingga mendekati Rp200.000, yang menunjukkan bahwa produk Wardah umumnya berada pada kategori kosmetik dengan harga yang relatif terjangkau bagi konsumen.

Secara keseluruhan, proses web scraping yang dilakukan pada kodingan ini berhasil mengumpulkan 40 entry data produk Wardah dari Lazada secara otomatis dan mengubahnya menjadi dataset yang terstruktur. Dengan memanfaatkan teknik web scraping, proses pengumpulan data yang sebelumnya harus dilakukan secara manual dapat dilakukan dengan lebih cepat, efisien, dan dalam jumlah data yang lebih besar.
"""